### ISSUE TITLE
Target with OS?

### ISSUE THREAD

**Issue by bootstraponline** [dev9com/parallel-webtest#5]
Does parallel-webtest allow specifying the operating system for the target browser to run on?

**Comment by yurodivuie** [comment]
Our tests aren't currently parameterized by OS, but it's possible to specify them using a map of desired capabilities in the constructor for the test class.  That's not as nice as being able to parameterize the operating system, though.  It shouldn't be too hard to add it as a third argument in the browser string that we use... I think that's a good idea for a feature.

I'll update this issue once it's implemented.

**Comment by will-iverson** [comment]
BTW, David, used to have OS in it in an old version.  Sauce changed the strings a bit.  Here's the current list:

http://saucelabs.com/docs/ondemand/browsers/env/java/se2/mac

**Comment by yurodivuie** [comment]
Yeah.. The trick is that we'll need to further customize the parameter used runner to accept multiple constructors.

Drake

**Comment by yurodivuie** [comment]
Version 1.3.1 has support for a constructor that accepts a platform string.  Documentation will be updated in the future, but it's working in tests.  The format is "browser:version:platform", where the platform string matches the platforms specified in org.openqa.selenium.Platform.

The available platforms are specified at http://saucelabs.com/docs/ondemand/browsers/.  When retrieving the "os" from Sauce Labs using the SauceREST client, the string returned differs from the string used in the parameters (they tend to be more specific, using "Windows 2003" instead of "WINDOWS", for example).  It's useful to keep in mind, but the method we use to specify the platform is via the DesiredCapabilities object (as recommended by Sauce Labs), which uses the selenium Platform object rather than the strings returned by Sauce Labs.
